POST http://localhost:5000/api/auth/registration/user/email
Content-Type: application/json

{
    "email":"1234567@gmail.com",
    "password":"1234567",
    "first_name":"1234567"
}

###
GET http://localhost:5000/api/auth/activate/email/701687

###
POST http://localhost:5000/api/auth/resend/activate/email
Content-Type: application/json

{
    "email":"123456@gmail.com"
}

###