POST http://localhost:5000/auth/registration/user/email
content-Type: application/json

{
    "email":"1234567@gmail.com",
    "password":"1234567",
    "first_name":"1234567"
}
###
GET http://localhost:5000/auth/activate/email/701687
###
POST http://localhost:5000/auth/resend/activate/email
content-Type: application/json

{
    "email":"1234567@gmail.com"
}
###
POST http://localhost:5000/auth/login/email
content-Type: application/json

{
    "email":"1234567@gmail.com",
    "password":"1234567"
}